### ISSUE TITLE
Grand total is incorrect, burger menu missing from shielded balance page

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-reference-wallet-ios#190]
ISSUE UPDATED ON MARCH 2ND TO AVOID CONFUSION

**Bug Description**

1. In Accounts overview: 
- Balance on top will add all the public balances of the accounts
- At disposal on top will add the at disposal balances of the accounts
- Each row will show the public balance + at disposal balance

2. In Accounts details:
- the total will show the public balance (finalised public balance minus the pending transactions on public balance) = no change in calculation of public balance)
- the at Disposal will show the (total - max(stakedAmount, releaseScheduleTotal)) = no change in calculation of atDisposal
- add burger menu for shielded balance
- rename address to receive

3. The shielded top total will show the shielded balance (= finalised shielded balance minus pending transactions on shielded balance)

5. Send funds
- if we send fund from the public balance we show **public balance** and **at disposal**
- if we send funds from the shielded balance we show **at disposal of public balance** + **shielded balance**

**!!!! Delegation stake will NOT be included in March release**

**Versions**
- Software Version: Testnet 2.0
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE

**Comment by ruxandra-constantinescu** [comment]
@mh-concordium (I would tag Jens Ager, but I can't - maybe you can?)
 1. you are right about something being incorrect, but I believe it is the Total of the Test account. From what we I understood from the discussion with Jens Ager, the account overview should not have any mention/trace of the shielded balance. So the Total of the Test account should actually say 1699.534157
 2. I understood that the + shielded should not be shown in the total public balance (it wasn't before either) 
 3. - will rename address to receive
 - I'll fix the burger menu

**Comment by ruxandra-constantinescu** [comment]
@jens-concordium what about the 1st point? Do we update the Grand total to include what can de crypted from shielded or do we update the total for each account to not include it?

**Comment by jens-concordium** [comment]
@ruxandra-constantinescu, we should make it so the grand total doesn't include the shielded balance. @mh-concordium is making a sketch with an overview, which we can use as a reference.

**Comment by mh-concordium** [comment]
Okay, now we all have the same understanding of the balances and how should we use them I have documented in on this image. I will post the same image to Android Wallet Repo.

<img width="3183" alt="Updated balances" src="https://user-images.githubusercontent.com/98821384/156165038-d9335828-5dd1-4d6a-9b08-dec9cbde8ab7.png">

**Comment by ruxandra-constantinescu** [comment]
@mh-concordium After discussing it with @jens-concordium  my understanding is:
1. In Accounts overview: 
- Balance on top will add all the public balances of the accounts
- At disposal on top will add the at disposal balances of the accounts
- Each row will show the public balance + at disposal balance

2. In Accounts details:
- the total will show the public balance (finalised public balance minus the pending transactions on public balance) = no change in calculation of public balance)
- the at Disposal will show the (total - max(stakedAmount, releaseScheduleTotal)) = no change in calculation of atDisposal
- add burger menu for shielded balance
- rename address to receive

3. The shielded balance will show the shielded balance (= finalized shileded minus pending transactions on shielded balance)

5. Send funds
- if we send fund from the public balance we show **public balance** and **at disposal**
- if we send funds from the shielded balance we show **public balance** + **shielded balance**

**!!!! Delegation stake will NOT be included in March release**

@mh-concordium @jens-concordium Can you confirm? And if so, can you update the description of the issue on both ios and Android in order to avoid confusion

**Comment by jens-concordium** [comment]
@ruxandra-constantinescu, yep that is correct, with the exception of the second point in 4, where it must be at **disposal on public balance** + **shielded balance**. 

I will update both this issue and the one on Android with your list Rux, including the difference mentioned in this comment.

@mh-concordium, fyi.

**Comment by ruxandra-constantinescu** [comment]
@jens-concordium I'll update my comment to reflect it and I'll post it on the Android issue as well

**Comment by mh-concordium** [comment]
Verified. Balances are added correctly now.
Scheduled transfer balance is added to grand total.
Readme balances are removed from at disposal balance but are still visible in grand total.
Total currently at disposal is a sum of all accounts at disposal amount.
Shielded balance is separated. 

**Versions**
- Software Version: Testnet 2.0.0 (36)
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE
