### ISSUE TITLE
Delegation status page not automatically updating upon finalization.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-reference-wallet-ios#291]
**Bug Description**

The delegation status page is not automatically updating upon finalization. 

**Steps to Reproduce**

- Register delegation
- Immediately go to the delegation status page

**Expected Result**
The page refreshes after a finalization has occurred.

**Actual Result**
It does not. The status page keeps saying "Waiting for transaction to finalize".

**Versions**
3.0.0 (50)

**Comment by Niljak** [comment]
Just tested this, it does update but the poll interval is perhaps longer than expected. Currently we poll every minute that you are on the delegation status page same as with other places in the app.

**Comment by EmilLa1** [comment]
I see. 

What can be the cause for this then? (Note the time in the upper left corner). 

![IMG_5219](https://user-images.githubusercontent.com/39825288/175233970-262cf1e2-2718-46a2-af9a-fb6501d545d9.PNG)
![File (2)](https://user-images.githubusercontent.com/39825288/175233983-560b9abd-16cc-4242-8795-7d6ccce60bc4.jpg)

**Comment by EmilLa1** [comment]
Note. the block which contained this transaction was finalized at `08:42:48`.

**Comment by Niljak** [comment]
Did you put the app in the background while on the status screen?

**Comment by EmilLa1** [comment]
No, the app was open throughout the duration I took these two screenshots.

**Comment by mh-concordium** [comment]
Tested on 3.0.0 (52).
Add delegation.
Update delegation.
Stop delegation.

I can confirm that the status page updates after a minute. Given that the block is on average finalized after ~12 seconds, this page transition could appear much faster. 

Even though a minute can be quite long time to wait, I think we shouldn't fix this issue further because issue will be solved anyway by future implementations in Mobile Wallets. @jens-concordium  @concordium-cl

**Comment by jens-concordium** [comment]
I agree. A minute is fine for now.
